typography_spectrum: 0.80689
color:
  brandColors:
    - '#030303'
    - '#ECF8EE'
    - '#D1C1A7'
    - '#825E48'
    - '#E4839F'
  brandStrength: 0.3195938
  lightness: 0.620669
  saturation: 1
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.75042
analytics:
  google: null
  facebook: null
  twitter: null
author:
  email: kim@millcottagephoto.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/bf667ea2-2213-437c-b6d5-be668357af5d.png
name: Kim Sayre Photography
cta:
  domain: null
  bucket: null
  version: null
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: 'Kim Sayre Photography - 415-515-6370 Weddings, Portraits and Events '
purpose: []
