typography_spectrum: 0.21958514023572206
color:
  brandColors:
    - '#030303'
    - '#ECF8EE'
    - '#D1C1A7'
    - '#825E48'
    - '#E4839F'
  brandStrength: 0.3195938
  lightness: 0.620669
  saturation: 1
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.6376741656567901
analytics:
  google: null
  facebook: null
  twitter: null
author:
  email: kim@millcottagephoto.com
  name: Kim Sayre
  url: 'https://delicious-images.smugmug.com/'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/31fa906f-4f2f-415e-b516-579660498609.jpg
name: Kim Sayre Photography
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Portfolio
    url: 'https://delicious-images.smugmug.com/'
    type: external
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: 'Kim Sayre Photography   Weddings, Portraits and Events '
description: 'San Francisco and Grass Valley, California'
purpose: []
