name: Kim Sayre Photography
favicon: null
layout_spectrum: 0.73603
typography_spectrum: 0.32402
title: Kim Sayre Photography - Grass Valley and San Francisco Portraits and Events
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0d0c08'
    - '#a9d0df'
    - '#8e95a8'
    - '#5f6f7e'
    - '#553320'
  brandStrength: 0
  lightness: 0.625
  saturation: 1
  rhythmicContrast: 0.75
purpose: []
